### ISSUE TITLE
ReferenceError: writeNumberCached is not defined in writeToStream.js:14:19

### ISSUE THREAD

**Issue by Apollon77** [mqttjs/mqtt-packet#32]
ReferenceError: writeNumberCached is not defined
    at Object.<anonymous> (/home/travis/build/ioBroker/ioBroker.mqtt/tmp/node_modules/iobroker.mqtt/node_modules/mqtt-connection/node_modules/mqtt-packet/writeToStream.js:14:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/ioBroker/ioBroker.mqtt/tmp/node_modules/iobroker.mqtt/node_modules/mqtt-connection/node_modules/mqtt-packet/generate.js:4:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by Apollon77** [comment]
... in all node versions. Any iea?!

**Comment by mcollina** [comment]
Not sure, it's in here: https://github.com/mqttjs/mqtt-packet/blob/master/writeToStream.js#L551-L553.

**Comment by Apollon77** [comment]
Found it too, but crashes interestingly in my application ...

**Comment by mcollina** [comment]
Can you reproduce just using mqtt-packet or mqtt-connection?

**Comment by Apollon77** [comment]
my project uses mqtt-connection 3.1.0 ... let me see if upgrade to 3.2.0 brings something

**Comment by Apollon77** [comment]
problem found ... the file was replaced locally ... whyever.. SOrry
