### ISSUE TITLE
TypeError: Invalid data, chunk must be a string or buffer, not undefined

### ISSUE THREAD

**Issue by eladnava** [mqttjs/mqtt-packet#44]
Hi @mcollina,
Hope you are doing well.

I've been getting this unhandled exception in production randomly:

```
TypeError: Invalid data, chunk must be a string or buffer, not undefined
    at Socket.write (net.js:704:11)
    at writeNumberCached (/home/ubuntu/app/node_modules/mqtt-packet/writeToStream.js:826:17)
    at publish (/home/ubuntu/app/node_modules/mqtt-packet/writeToStream.js:349:16)
    at generate (/home/ubuntu/app/node_modules/mqtt-packet/writeToStream.js:35:14)
    at Writable.write [as _write] (/home/ubuntu/app/node_modules/mqtt-connection/lib/writeToStre$
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at Writable.write (_stream_writable.js:290:11)
    at Connection.Duplexify._write (/home/ubuntu/app/node_modules/duplexify/index.js:208:22)
    at doWrite (/home/ubuntu/app/node_modules/readable-stream/lib/_stream_writable.js:428:64)
```

The line throwing this exception:
https://github.com/mqttjs/mqtt-packet/blob/33243c5cdbb799a1fd978412fa66db2f1a6609ed/writeToStream.js#L825-L827

It appears the `numCache` may not have been populated when `writeNumberCached` was called. Any idea why or how this could happen?

A fix could look like this:

```
function writeNumberCached (stream, number) {
  return stream.write(numCache[number] || generateNumber(number))
}
```

**Comment by mcollina** [comment]
This is extremely strange and unusual. Are you able to reproduce with a short example?

**Comment by eladnava** [comment]
@mcollina unfortunately not, this happens randomly in production and I could only attribute it to a rogue client sending weird packets or a passively disconnecting client.

Maybe this is something that only happens in my case. I applied the patch in production now and will see if everything works well after.

**Comment by eladnava** [comment]
@mcollina After applying the fix I mentioned (falling back to `generateNumber(number)` in case `numCache[number]` is `null`) we now have more insight into the issue as the `number` being passed into `writeNumberCached` seems to be out of range of `uint8` as per the following error:

```
buffer.js:1185
    throw new TypeError('"value" argument is out of bounds');
    ^

TypeError: "value" argument is out of bounds
    at checkInt (buffer.js:1185:11)
    at Buffer.writeUInt8 (buffer.js:1233:5)
    at generateBuffer (/home/node/app/node_modules/mqtt-packet/numbers.js:9:10)
    at writeNumberCached (/home/node/app/node_modules/mqtt-packet/writeToStream.js:826:43)
    at publish (/home/node/app/node_modules/mqtt-packet/writeToStream.js:349:16)
    at generate (/home/node/app/node_modules/mqtt-packet/writeToStream.js:35:14)
    at Writable.write [as _write] (/home/node/app/node_modules/mqtt-connection/lib/writeToStre$
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at Writable.write (_stream_writable.js:290:11)
```

Any idea why `writeNumberCached` was called with an out-of-range `number` param?

**Comment by eladnava** [comment]
I was able to trace down and isolate the issue to my broker code calling `client.publish()` with a `messageId` of `65536` when the last valid messageId is `65535`.

My bad. 😜
